# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "CPyCppyy" = super.buildPythonPackage rec {
    pname = "CPyCppyy";
    version = "1.12.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ab/bf/947395ad56390b626d4b533e2772eecbc07b857cd241d9497cd0f4741334/CPyCppyy-1.12.16.tar.gz";
      sha256 = "00j2kvgfq2fsxjnlrpz9c0akqjal5y3dm7a9xivjga6159jlba09";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."cppyy-cling"
      self."cppyy-backend"
      self."setuptools"
      self."wheel"
    ];
    propagatedBuildInputs = [
      self."cppyy-backend"
      self."cppyy-cling"
    ];
  };
  "cppyy" = super.buildPythonPackage rec {
    pname = "cppyy";
    version = "3.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/28/76ea59829239a8bc587ddc9e581d4a943f7daa24b7d1a13597870a73b726/cppyy-3.1.2.tar.gz";
      sha256 = "16ziq78r7fh9vp1hcgsvxy47hsiwrh5mwrfm8h7m3q82my2d2dvr";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
    ];
    propagatedBuildInputs = [
      self."CPyCppyy"
      self."cppyy-backend"
      self."cppyy-cling"
    ];
  };
  "cppyy-backend" = super.buildPythonPackage rec {
    pname = "cppyy-backend";
    version = "1.15.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/fe/3dc515b384afec3801f59e6675120a6ccfe2ad40fab13cfd0e5db270a924/cppyy-backend-1.15.2.tar.gz";
      sha256 = "1z1mv39k6abhl3kaqsnix210125cw962f6x6k5lx4h7ayrlw23ld";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cppyy-cling"
    ];
  };
  "cppyy-cling" = super.buildPythonPackage rec {
    pname = "cppyy-cling";
    version = "6.30.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/d6/d73cc0698182034d8f03fd96efa581910d2aaa7379a84a2f1f91231bdae4/cppyy-cling-6.30.0.tar.gz";
      sha256 = "1w9az42bm6c9hr6wsbzhawig15325kfb609076rqwqfbli8hb7jx";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [ pkgs.cmake ];
    propagatedBuildInputs = [];
  };
}
